from app.models.airlines import Airline
from app.models.aircrafts import Aircraft
from app.models.flights import Flight
from app.models.passengers import Passenger
from app.models.pilots import Pilot
from app.models.cabin_crews import CabinCrew
from app.models.flight_pilot import FlightPilot
from app.models.flight_crews import FlightCrew
from app.models.airport_distances import AirportDistance
from app.models.pilot_standards import PilotStandard
from app.models.cabin_crew_standards import CabinCrewStandard
